# access the hexo editor directly
local: true

# the username to login hexo editor
username: hexo

# the password for logining hexo editor
password: imyouradmin

# the blog directory
base_dir: /Users/kimcp/Documents/blog/blogsource 

# port
port: 2048
